---
- name: Allow current user to use sudo without password
  become: true
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ ansible_user_id }}-nopasswd"
    content: |
      {{ ansible_user_id }} ALL=(ALL) NOPASSWD:ALL
    owner: root
    group: root
    mode: "0440"
    validate: "visudo -cf %s"
