---
- name: Install Zed via Flatpak
  become: true
  community.general.flatpak:
    name: dev.zed.Zed
    method: user
    state: present
  tags:
    - zed

- name: Setup alias for zed zsh
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'alias zed="flatpak run dev.zed.Zed"'
    create: true
    state: present
  tags:
    - zed

- name: Inform user to reload shell
  ansible.builtin.debug:
    msg: "Alias created. Run 'source /home/omen/.zshrc' or restart your terminal to use 'zed'."
  tags:
    - zed
